# Basic Home Assistant configuration

homeassistant:
  name: Home Assistant
  time_zone: UTC
  latitude: 32.0
  longitude: 34.8
  elevation: 0
  unit_system: metric

default_config:

frontend:

http:
  server_port: 8123

lovelace:
  resources:
    - url: /local/weather-alerts-card.js
      type: module

binary_sensor:
  - platform: meteoalarm
    country: "netherlands"
    province: "Texel"
