services:
  homeassistant:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: weather-alerts-card-ha
    restart: unless-stopped
    network_mode: host
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "8123:8123"
    volumes:
      - ../config:/config
      - ../dist/weather-alerts-card.js:/config/www/weather-alerts-card.js:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=UTC
