type TranslationMap = Record<string, string>;

const en: TranslationMap = {
  // Card UI
  'card.no_alerts': 'No active alerts.',
  'card.sensor_unavailable': 'Alert sensor is {state}.',
  'card.preview': 'Preview',
  'card.read_details': 'Read Details',
  'card.open_source': 'Open {provider} Source',
  'card.active': 'Active',
  'card.in_prep': 'In Prep',
  'card.zones_count': '{count} zones',
  'card.zone_count_singular': '{count} zone',

  // Detail labels
  'detail.issued': 'Issued',
  'detail.onset': 'Onset',
  'detail.expires': 'Expires',
  'detail.area': 'Area',
  'detail.description': 'Description',
  'detail.instructions': 'Instructions',

  // Progress bar
  'progress.start': 'Start',
  'progress.now': 'Now',
  'progress.end': 'End',
  'progress.ongoing': 'Ongoing',
  'progress.expires_in': 'expires {time}',
  'progress.starts_in': 'starts {time}',
  'progress.expires_in_label': 'Expires in',
  'progress.starts_in_label': 'Starts in',
  'progress.tbd': 'TBD',
  'progress.na': 'N/A',
  'progress.expired_label': 'Expired',
  'progress.expired_ago': 'expired {time} ago',
  'progress.compact_active': 'for {time}',
  'progress.compact_prep': 'in {time}',
  'progress.compact_ongoing': 'ongoing',
  'progress.compact_expired': 'expired {time} ago',

  // Relative time
  'time.just_now': 'just now',
  'time.in_less_than_1m': 'in <1m',
  'time.minutes_ago': '{m}m ago',
  'time.in_minutes': 'in {m}m',
  'time.hours_ago': '{dur} ago',
  'time.in_hours': 'in {dur}',
  'time.days_ago': '{d}d ago',
  'time.in_days': 'in {d}d',

  // Badge labels
  'badge.severity_extreme': 'Extreme',
  'badge.severity_severe': 'Severe',
  'badge.severity_moderate': 'Moderate',
  'badge.severity_minor': 'Minor',
  'badge.severity_unknown': 'Unknown',
  'badge.certainty_observed': 'Observed',
  'badge.certainty_likely': 'Likely',
  'badge.certainty_possible': 'Possible',
  'badge.certainty_unlikely': 'Unlikely',
  'badge.certainty_unknown': 'Unknown',

  // Editor
  'editor.entity': 'Entity (required)',
  'editor.title': 'Title (optional)',
  'editor.provider': 'Alert provider',
  'editor.provider_auto': 'Auto-detect',
  'editor.provider_nws': 'NWS (United States)',
  'editor.provider_bom': 'BoM (Australia)',
  'editor.provider_meteoalarm': 'MeteoAlarm (Europe)',
  'editor.provider_pirateweather': 'PirateWeather',
  'editor.zones': 'Zones (optional)',
  'editor.zones_helper': 'Comma-separated zone codes, e.g. COC059, COZ039 (NWS) or NSW_FL049 (BoM)',
  'editor.event_codes': 'Event codes (optional)',
  'editor.event_codes_helper': 'Comma-separated NWS event codes, e.g. TOW, SVW, FFW',
  'editor.exclude_event_codes': 'Exclude event codes (optional)',
  'editor.exclude_event_codes_helper': 'Comma-separated NWS event codes to hide, e.g. SCY, SCW',
  'editor.sort_order': 'Sort order',
  'editor.sort_default': 'Default',
  'editor.sort_onset': 'Onset time',
  'editor.sort_severity': 'Severity',
  'editor.color_theme': 'Color theme',
  'editor.color_severity': 'Severity-based',
  'editor.color_nws': 'NWS Official',
  'editor.color_meteoalarm': 'MeteoAlarm Awareness',
  'editor.timezone': 'Timezone',
  'editor.tz_server': 'Server (Home Assistant)',
  'editor.tz_browser': 'Browser (local device)',
  'editor.min_severity': 'Minimum severity',
  'editor.severity_all': 'All severities',
  'editor.severity_minor': 'Minor or higher',
  'editor.severity_moderate': 'Moderate or higher',
  'editor.severity_severe': 'Severe or higher',
  'editor.severity_extreme': 'Extreme only',
  'editor.animations': 'Enable animations',
  'editor.deduplicate': 'Deduplicate alerts',
  'editor.deduplicate_headlines': 'Deduplicate headlines',
  'editor.show_source_link': 'Show source link',
  'editor.compact': 'Compact layout',
  'editor.font_size': 'Font size',
  'editor.font_size_small': 'Small',
  'editor.font_size_default': 'Default',
  'editor.font_size_large': 'Large',
  'editor.font_size_x_large': 'Extra large',
  'editor.hide_expired': 'Hide expired alerts',
  'editor.hide_no_alerts': 'Hide card when there are no active alerts',
  'editor.show_preview': 'Show sample data',
  'editor.preview_hint': 'Preview card layout with placeholder alerts',
  'editor.entity_warning': 'Selected entity does not appear to contain weather alert data.',
};

const fr: TranslationMap = {
  // Card UI
  'card.no_alerts': 'Aucune alerte active.',
  'card.sensor_unavailable': 'Le capteur d\'alerte est {state}.',
  'card.preview': 'Apercu',
  'card.read_details': 'Lire les details',
  'card.open_source': 'Ouvrir la source {provider}',
  'card.active': 'Actif',
  'card.in_prep': 'En prep.',
  'card.zones_count': '{count} zones',
  'card.zone_count_singular': '{count} zone',

  // Detail labels
  'detail.issued': 'Emis',
  'detail.onset': 'Debut',
  'detail.expires': 'Expire',
  'detail.area': 'Zone',
  'detail.description': 'Description',
  'detail.instructions': 'Instructions',

  // Progress bar
  'progress.start': 'Debut',
  'progress.now': 'Maint.',
  'progress.end': 'Fin',
  'progress.ongoing': 'En cours',
  'progress.expires_in': 'expire {time}',
  'progress.starts_in': 'commence {time}',
  'progress.expires_in_label': 'Expire dans',
  'progress.starts_in_label': 'Commence dans',
  'progress.tbd': 'Ind.',
  'progress.na': 'N/D',
  'progress.expired_label': 'Expiré',
  'progress.expired_ago': 'expiré il y a {time}',
  'progress.compact_active': 'pour {time}',
  'progress.compact_prep': 'dans {time}',
  'progress.compact_ongoing': 'en cours',
  'progress.compact_expired': 'expiré il y a {time}',

  // Relative time
  'time.just_now': 'a l\'instant',
  'time.in_less_than_1m': 'dans <1m',
  'time.minutes_ago': 'il y a {m}m',
  'time.in_minutes': 'dans {m}m',
  'time.hours_ago': 'il y a {dur}',
  'time.in_hours': 'dans {dur}',
  'time.days_ago': 'il y a {d}j',
  'time.in_days': 'dans {d}j',

  // Badge labels
  'badge.severity_extreme': 'Extrême',
  'badge.severity_severe': 'Grave',
  'badge.severity_moderate': 'Modérée',
  'badge.severity_minor': 'Mineure',
  'badge.severity_unknown': 'Inconnue',
  'badge.certainty_observed': 'Observée',
  'badge.certainty_likely': 'Probable',
  'badge.certainty_possible': 'Possible',
  'badge.certainty_unlikely': 'Improbable',
  'badge.certainty_unknown': 'Inconnue',

  // Editor
  'editor.entity': 'Entite (requis)',
  'editor.title': 'Titre (optionnel)',
  'editor.provider': 'Fournisseur d\'alertes',
  'editor.provider_auto': 'Detection auto',
  'editor.provider_nws': 'NWS (Etats-Unis)',
  'editor.provider_bom': 'BoM (Australie)',
  'editor.provider_meteoalarm': 'MeteoAlarm (Europe)',
  'editor.provider_pirateweather': 'PirateWeather',
  'editor.zones': 'Zones (optionnel)',
  'editor.zones_helper': 'Codes de zone separes par des virgules, ex. COC059, COZ039 (NWS) ou NSW_FL049 (BoM)',
  'editor.event_codes': 'Codes d\'evenement (optionnel)',
  'editor.event_codes_helper': 'Codes d\'evenement NWS separes par des virgules, ex. TOW, SVW, FFW',
  'editor.exclude_event_codes': 'Exclure codes d\'evenement (optionnel)',
  'editor.exclude_event_codes_helper': 'Codes d\'evenement NWS a masquer, ex. SCY, SCW',
  'editor.sort_order': 'Ordre de tri',
  'editor.sort_default': 'Par defaut',
  'editor.sort_onset': 'Heure de debut',
  'editor.sort_severity': 'Gravite',
  'editor.color_theme': 'Theme de couleur',
  'editor.color_severity': 'Base sur la gravite',
  'editor.color_nws': 'NWS officiel',
  'editor.color_meteoalarm': 'MeteoAlarm Vigilance',
  'editor.timezone': 'Fuseau horaire',
  'editor.tz_server': 'Serveur (Home Assistant)',
  'editor.tz_browser': 'Navigateur (appareil local)',
  'editor.min_severity': 'Gravite minimale',
  'editor.severity_all': 'Toutes les gravites',
  'editor.severity_minor': 'Mineure ou plus',
  'editor.severity_moderate': 'Moderee ou plus',
  'editor.severity_severe': 'Grave ou plus',
  'editor.severity_extreme': 'Extreme uniquement',
  'editor.animations': 'Activer les animations',
  'editor.deduplicate': 'Dedupliquer les alertes',
  'editor.deduplicate_headlines': 'Dédupliquer les titres',
  'editor.show_source_link': 'Afficher le lien source',
  'editor.compact': 'Disposition compacte',
  'editor.font_size': 'Taille de police',
  'editor.font_size_small': 'Petit',
  'editor.font_size_default': 'Par défaut',
  'editor.font_size_large': 'Grand',
  'editor.font_size_x_large': 'Très grand',
  'editor.hide_expired': 'Masquer les alertes expirées',
  'editor.hide_no_alerts': 'Masquer la carte sans alertes',
  'editor.show_preview': 'Afficher les donnees exemples',
  'editor.preview_hint': 'Apercu de la disposition avec des alertes fictives',
  'editor.entity_warning': 'L\'entite selectionnee ne semble pas contenir de donnees d\'alerte meteo.',
};

const es: TranslationMap = {
  // Card UI
  'card.no_alerts': 'Sin alertas activas.',
  'card.sensor_unavailable': 'El sensor de alertas esta {state}.',
  'card.preview': 'Vista previa',
  'card.read_details': 'Leer detalles',
  'card.open_source': 'Abrir fuente {provider}',
  'card.active': 'Activo',
  'card.in_prep': 'En prep.',
  'card.zones_count': '{count} zonas',
  'card.zone_count_singular': '{count} zona',

  // Detail labels
  'detail.issued': 'Emitido',
  'detail.onset': 'Inicio',
  'detail.expires': 'Expira',
  'detail.area': 'Area',
  'detail.description': 'Descripcion',
  'detail.instructions': 'Instrucciones',

  // Progress bar
  'progress.start': 'Inicio',
  'progress.now': 'Ahora',
  'progress.end': 'Fin',
  'progress.ongoing': 'En curso',
  'progress.expires_in': 'expira {time}',
  'progress.starts_in': 'comienza {time}',
  'progress.expires_in_label': 'Expira en',
  'progress.starts_in_label': 'Comienza en',
  'progress.tbd': 'Pend.',
  'progress.na': 'N/D',
  'progress.expired_label': 'Expirada',
  'progress.expired_ago': 'expiró hace {time}',
  'progress.compact_active': 'por {time}',
  'progress.compact_prep': 'en {time}',
  'progress.compact_ongoing': 'en curso',
  'progress.compact_expired': 'expiró hace {time}',

  // Relative time
  'time.just_now': 'ahora mismo',
  'time.in_less_than_1m': 'en <1m',
  'time.minutes_ago': 'hace {m}m',
  'time.in_minutes': 'en {m}m',
  'time.hours_ago': 'hace {dur}',
  'time.in_hours': 'en {dur}',
  'time.days_ago': 'hace {d}d',
  'time.in_days': 'en {d}d',

  // Badge labels
  'badge.severity_extreme': 'Extrema',
  'badge.severity_severe': 'Grave',
  'badge.severity_moderate': 'Moderada',
  'badge.severity_minor': 'Menor',
  'badge.severity_unknown': 'Desconocida',
  'badge.certainty_observed': 'Observada',
  'badge.certainty_likely': 'Probable',
  'badge.certainty_possible': 'Posible',
  'badge.certainty_unlikely': 'Improbable',
  'badge.certainty_unknown': 'Desconocida',

  // Editor
  'editor.entity': 'Entidad (requerido)',
  'editor.title': 'Titulo (opcional)',
  'editor.provider': 'Proveedor de alertas',
  'editor.provider_auto': 'Deteccion auto',
  'editor.provider_nws': 'NWS (Estados Unidos)',
  'editor.provider_bom': 'BoM (Australia)',
  'editor.provider_meteoalarm': 'MeteoAlarm (Europa)',
  'editor.provider_pirateweather': 'PirateWeather',
  'editor.zones': 'Zonas (opcional)',
  'editor.zones_helper': 'Codigos de zona separados por comas, ej. COC059, COZ039 (NWS) o NSW_FL049 (BoM)',
  'editor.event_codes': 'Codigos de evento (opcional)',
  'editor.event_codes_helper': 'Codigos de evento NWS separados por comas, ej. TOW, SVW, FFW',
  'editor.exclude_event_codes': 'Excluir codigos de evento (opcional)',
  'editor.exclude_event_codes_helper': 'Codigos de evento NWS a ocultar, ej. SCY, SCW',
  'editor.sort_order': 'Orden',
  'editor.sort_default': 'Predeterminado',
  'editor.sort_onset': 'Hora de inicio',
  'editor.sort_severity': 'Gravedad',
  'editor.color_theme': 'Tema de color',
  'editor.color_severity': 'Basado en gravedad',
  'editor.color_nws': 'NWS oficial',
  'editor.color_meteoalarm': 'MeteoAlarm Conciencia',
  'editor.timezone': 'Zona horaria',
  'editor.tz_server': 'Servidor (Home Assistant)',
  'editor.tz_browser': 'Navegador (dispositivo local)',
  'editor.min_severity': 'Gravedad minima',
  'editor.severity_all': 'Todas las gravedades',
  'editor.severity_minor': 'Menor o superior',
  'editor.severity_moderate': 'Moderada o superior',
  'editor.severity_severe': 'Grave o superior',
  'editor.severity_extreme': 'Solo extrema',
  'editor.animations': 'Activar animaciones',
  'editor.deduplicate': 'Deduplicar alertas',
  'editor.deduplicate_headlines': 'Deduplicar titulares',
  'editor.show_source_link': 'Mostrar enlace de fuente',
  'editor.compact': 'Disposicion compacta',
  'editor.font_size': 'Tamaño de fuente',
  'editor.font_size_small': 'Pequeño',
  'editor.font_size_default': 'Predeterminado',
  'editor.font_size_large': 'Grande',
  'editor.font_size_x_large': 'Extra grande',
  'editor.hide_expired': 'Ocultar alertas expiradas',
  'editor.hide_no_alerts': 'Ocultar tarjeta sin alertas',
  'editor.show_preview': 'Mostrar datos de ejemplo',
  'editor.preview_hint': 'Vista previa con alertas de ejemplo',
  'editor.entity_warning': 'La entidad seleccionada no parece contener datos de alerta meteorologica.',
};

const it: TranslationMap = {
  // Card UI
  'card.no_alerts': 'Nessuna allerta attiva.',
  'card.sensor_unavailable': 'Il sensore di allerta è {state}.',
  'card.preview': 'Anteprima',
  'card.read_details': 'Leggi dettagli',
  'card.open_source': 'Apri fonte {provider}',
  'card.active': 'Attiva',
  'card.in_prep': 'In prep.',
  'card.zones_count': '{count} zone',
  'card.zone_count_singular': '{count} zona',

  // Detail labels
  'detail.issued': 'Emessa',
  'detail.onset': 'Inizio',
  'detail.expires': 'Scadenza',
  'detail.area': 'Area',
  'detail.description': 'Descrizione',
  'detail.instructions': 'Istruzioni',

  // Progress bar
  'progress.start': 'Inizio',
  'progress.now': 'Ora',
  'progress.end': 'Fine',
  'progress.ongoing': 'In corso',
  'progress.expires_in': 'scade {time}',
  'progress.starts_in': 'inizia {time}',
  'progress.expires_in_label': 'Scade tra',
  'progress.starts_in_label': 'Inizia tra',
  'progress.tbd': 'N.D.',
  'progress.na': 'N/D',
  'progress.expired_label': 'Scaduta',
  'progress.expired_ago': 'scaduta {time} fa',
  'progress.compact_active': 'per {time}',
  'progress.compact_prep': 'tra {time}',
  'progress.compact_ongoing': 'in corso',
  'progress.compact_expired': 'scaduta {time} fa',

  // Relative time
  'time.just_now': 'proprio ora',
  'time.in_less_than_1m': 'in <1m',
  'time.minutes_ago': '{m}m fa',
  'time.in_minutes': 'in {m}m',
  'time.hours_ago': '{dur} fa',
  'time.in_hours': 'in {dur}',
  'time.days_ago': '{d}g fa',
  'time.in_days': 'in {d}g',

  // Badge labels
  'badge.severity_extreme': 'Estrema',
  'badge.severity_severe': 'Grave',
  'badge.severity_moderate': 'Moderata',
  'badge.severity_minor': 'Lieve',
  'badge.severity_unknown': 'Sconosciuta',
  'badge.certainty_observed': 'Osservata',
  'badge.certainty_likely': 'Probabile',
  'badge.certainty_possible': 'Possibile',
  'badge.certainty_unlikely': 'Improbabile',
  'badge.certainty_unknown': 'Sconosciuta',

  // Editor
  'editor.entity': 'Entità (obbligatorio)',
  'editor.title': 'Titolo (opzionale)',
  'editor.provider': 'Fornitore allerte',
  'editor.provider_auto': 'Rilevamento automatico',
  'editor.provider_nws': 'NWS (Stati Uniti)',
  'editor.provider_bom': 'BoM (Australia)',
  'editor.provider_meteoalarm': 'MeteoAlarm (Europa)',
  'editor.provider_pirateweather': 'PirateWeather',
  'editor.zones': 'Zone (opzionale)',
  'editor.zones_helper': 'Codici zona separati da virgola, es. COC059, COZ039 (NWS) o NSW_FL049 (BoM)',
  'editor.event_codes': 'Codici evento (opzionale)',
  'editor.event_codes_helper': 'Codici evento NWS separati da virgola, es. TOW, SVW, FFW',
  'editor.exclude_event_codes': 'Escludi codici evento (opzionale)',
  'editor.exclude_event_codes_helper': 'Codici evento NWS da nascondere, es. SCY, SCW',
  'editor.sort_order': 'Ordinamento',
  'editor.sort_default': 'Predefinito',
  'editor.sort_onset': 'Ora di inizio',
  'editor.sort_severity': 'Gravità',
  'editor.color_theme': 'Tema colori',
  'editor.color_severity': 'Basato sulla gravità',
  'editor.color_nws': 'NWS ufficiale',
  'editor.color_meteoalarm': 'MeteoAlarm Livelli',
  'editor.timezone': 'Fuso orario',
  'editor.tz_server': 'Server (Home Assistant)',
  'editor.tz_browser': 'Browser (dispositivo locale)',
  'editor.min_severity': 'Gravità minima',
  'editor.severity_all': 'Tutte le gravità',
  'editor.severity_minor': 'Lieve o superiore',
  'editor.severity_moderate': 'Moderata o superiore',
  'editor.severity_severe': 'Grave o superiore',
  'editor.severity_extreme': 'Solo estrema',
  'editor.animations': 'Abilita animazioni',
  'editor.deduplicate': 'Deduplica allerte',
  'editor.deduplicate_headlines': 'Deduplica titoli',
  'editor.show_source_link': 'Mostra link alla fonte',
  'editor.compact': 'Layout compatto',
  'editor.font_size': 'Dimensione testo',
  'editor.font_size_small': 'Piccolo',
  'editor.font_size_default': 'Predefinito',
  'editor.font_size_large': 'Grande',
  'editor.font_size_x_large': 'Molto grande',
  'editor.hide_expired': 'Nascondi allerte scadute',
  'editor.hide_no_alerts': 'Nascondi scheda senza allerte',
  'editor.show_preview': 'Mostra dati di esempio',
  'editor.preview_hint': 'Anteprima del layout con allerte di esempio',
  'editor.entity_warning': 'L\'entità selezionata non sembra contenere dati di allerta meteo.',
};

const de: TranslationMap = {
  // Card UI
  'card.no_alerts': 'Keine aktiven Warnungen.',
  'card.sensor_unavailable': 'Der Warnsensor ist {state}.',
  'card.preview': 'Vorschau',
  'card.read_details': 'Details lesen',
  'card.open_source': '{provider}-Quelle öffnen',
  'card.active': 'Aktiv',
  'card.in_prep': 'In Vorb.',
  'card.zones_count': '{count} Zonen',
  'card.zone_count_singular': '{count} Zone',

  // Detail labels
  'detail.issued': 'Ausgegeben',
  'detail.onset': 'Beginn',
  'detail.expires': 'Ablauf',
  'detail.area': 'Gebiet',
  'detail.description': 'Beschreibung',
  'detail.instructions': 'Hinweise',

  // Progress bar
  'progress.start': 'Start',
  'progress.now': 'Jetzt',
  'progress.end': 'Ende',
  'progress.ongoing': 'Laufend',
  'progress.expires_in': 'endet {time}',
  'progress.starts_in': 'beginnt {time}',
  'progress.expires_in_label': 'Endet in',
  'progress.starts_in_label': 'Beginnt in',
  'progress.tbd': 'Offen',
  'progress.na': 'K. A.',
  'progress.expired_label': 'Abgelaufen',
  'progress.expired_ago': 'abgelaufen vor {time}',
  'progress.compact_active': 'für {time}',
  'progress.compact_prep': 'in {time}',
  'progress.compact_ongoing': 'laufend',
  'progress.compact_expired': 'abgelaufen vor {time}',

  // Relative time
  'time.just_now': 'gerade eben',
  'time.in_less_than_1m': 'in <1 Min',
  'time.minutes_ago': 'vor {m} Min',
  'time.in_minutes': 'in {m} Min',
  'time.hours_ago': 'vor {dur}',
  'time.in_hours': 'in {dur}',
  'time.days_ago': 'vor {d} T',
  'time.in_days': 'in {d} T',

  // Badge labels
  'badge.severity_extreme': 'Extrem',
  'badge.severity_severe': 'Schwer',
  'badge.severity_moderate': 'Mäßig',
  'badge.severity_minor': 'Gering',
  'badge.severity_unknown': 'Unbekannt',
  'badge.certainty_observed': 'Beobachtet',
  'badge.certainty_likely': 'Wahrscheinlich',
  'badge.certainty_possible': 'Möglich',
  'badge.certainty_unlikely': 'Unwahrscheinlich',
  'badge.certainty_unknown': 'Unbekannt',

  // Editor
  'editor.entity': 'Entität (erforderlich)',
  'editor.title': 'Titel (optional)',
  'editor.provider': 'Warnanbieter',
  'editor.provider_auto': 'Automatisch erkennen',
  'editor.provider_nws': 'NWS (USA)',
  'editor.provider_bom': 'BoM (Australien)',
  'editor.provider_meteoalarm': 'MeteoAlarm (Europa)',
  'editor.provider_pirateweather': 'PirateWeather',
  'editor.zones': 'Zonen (optional)',
  'editor.zones_helper': 'Kommagetrennte Zonencodes, z. B. COC059, COZ039 (NWS) oder NSW_FL049 (BoM)',
  'editor.event_codes': 'Ereigniscodes (optional)',
  'editor.event_codes_helper': 'Kommagetrennte NWS-Ereigniscodes, z. B. TOW, SVW, FFW',
  'editor.exclude_event_codes': 'Ereigniscodes ausschließen (optional)',
  'editor.exclude_event_codes_helper': 'Kommagetrennte NWS-Ereigniscodes zum Ausblenden, z. B. SCY, SCW',
  'editor.sort_order': 'Sortierung',
  'editor.sort_default': 'Standard',
  'editor.sort_onset': 'Beginnzeit',
  'editor.sort_severity': 'Schweregrad',
  'editor.color_theme': 'Farbschema',
  'editor.color_severity': 'Nach Schweregrad',
  'editor.color_nws': 'NWS offiziell',
  'editor.color_meteoalarm': 'MeteoAlarm Warnstufen',
  'editor.timezone': 'Zeitzone',
  'editor.tz_server': 'Server (Home Assistant)',
  'editor.tz_browser': 'Browser (lokales Gerät)',
  'editor.min_severity': 'Mindestschweregrad',
  'editor.severity_all': 'Alle Schweregrade',
  'editor.severity_minor': 'Gering oder höher',
  'editor.severity_moderate': 'Mäßig oder höher',
  'editor.severity_severe': 'Schwer oder höher',
  'editor.severity_extreme': 'Nur extrem',
  'editor.animations': 'Animationen aktivieren',
  'editor.deduplicate': 'Warnungen deduplizieren',
  'editor.deduplicate_headlines': 'Überschriften deduplizieren',
  'editor.show_source_link': 'Quelllink anzeigen',
  'editor.compact': 'Kompaktes Layout',
  'editor.font_size': 'Schriftgröße',
  'editor.font_size_small': 'Klein',
  'editor.font_size_default': 'Standard',
  'editor.font_size_large': 'Groß',
  'editor.font_size_x_large': 'Sehr groß',
  'editor.hide_expired': 'Abgelaufene Warnungen ausblenden',
  'editor.hide_no_alerts': 'Karte ohne aktive Warnungen ausblenden',
  'editor.show_preview': 'Beispieldaten anzeigen',
  'editor.preview_hint': 'Kartenlayout mit Beispielwarnungen anzeigen',
  'editor.entity_warning': 'Die ausgewählte Entität scheint keine Wetterwarnungsdaten zu enthalten.',
};

const translations: Record<string, TranslationMap> = { en, fr, es, it, de };

export function t(key: string, lang: string, params?: Record<string, string | number>): string {
  const baseLang = lang.split('-')[0].toLowerCase();
  const map = translations[baseLang] || translations.en;
  let value = map[key] ?? translations.en[key] ?? key;

  if (params) {
    for (const [k, v] of Object.entries(params)) {
      value = value.replace(`{${k}}`, String(v));
    }
  }

  return value;
}
